### PR TITLE
Multiple features added

### PR DESCRIPTION
**Pull request by 813gan**
New staff:
1. URL sanitizer
2. quiet mode
3. Command line parser
4. 'lurk mode'
    In 'lurk mode' script search selected board for threads that have subject or comment matching regular expression

### CODE REVIEW

**Comment by wewman** [comment]
Hey cool stuff. I will test it tomorrow at work and see what's up!

Also, for some reason, some WEBMs have different tails and may get deleted as well. I don't know if 4chan changes anything to make it specific, but when I was using that webm cleaner for webms from gelbooru, it was deleting already 100% completed webms.

Should we just take it off do you think?

Thank you.

**Comment by 813gan** [comment]
I had never saw broken file, I'm unable to even test this feature.
4chan API provide MD5 sums. I think we could use it, but I have no idea how to decode(?) it. 
[https://github.com/4chan/4chan-API#posts-object](url) 

> text (24 character, packed base64 MD5 hash)

Do you know how to make this 'packed b64 MD5' usable?
EDIT:
gelbooru provide MD5 too.

**Comment by wewman** [comment]
Hey sorry I didn't get to test it yet, I have two exams I'm preparing for.

We can use md5sum and grep the given md5 from the api.

EDIT: Oh wait nevermind, I'll have a look into it more, the base64 returns some weird binary. Guess they hare encoding extra stuff there.
EDIT: Nevermind I'm being an idiot here, I'll try and find what that 24 character packed base64 md5 hash means, since md5 is when I get time.

EDIT: Figured it out, I looked it up and came across some threads:
https://archive.rebeccablacktech.com/g/thread/32501517
http://4chanarchives.com/board/g/thread/51531294

This is what's going on:
When you decode the base64, you get a malformed binary right? But when you dump it as hex, you get the same thing as what you get form md5sum:

echo "ncAfzy+Rb+FQYHU9bSZ71w==" | base64 -d | xxd
Note that xxd formats it with spaces, I'm sure there's a way around getting it to display only as one-liner.
When we do md5sum, the md5hash appears as the same thing in the hex from the xxd's return.

**Comment by wewman** [comment]
Ok we can clean stuff up better doing this:

`echo "ncAfzy+Rb+FQYHU9bSZ71w==" | base64 -d | xxd -p -l 16`
To get the md5 checksum of the image itself.
Then, grep the md5sum of the images that we have. We can make either a new file that contains the filename with the hash, or do it all in memory (which is my initial intuition, less files possible) Or just put them next to the URLs of each image.

**Comment by 813gan** [comment]
Thanks for research, xxd is black magic for me.
I will implement hash based verification in near future and i will try to remove temporary files. If it will be to hard we can just put them in tmpfs ;)

**Comment by wewman** [comment]
By the way, I tested the lurk mode you had, but I got an error.

Can you show me a demo or an example? What kind of regex are you expecting?

**Comment by 813gan** [comment]
What error did you get?
jq use PCRE expressions.
Some examples: 
`$ 4bash.sh -l wg mountains`
`$ 4bash.sh -l wg '(Sci-fi)|(Cyberpunk)|(Star Wars)'`

**Comment by wewman** [comment]
```error: syntax error, unexpected '?', expecting $end
.[] | .threads | .[] | if (.com + "\n" + .sub | test( $regrex;"i" )) then .no  else empty end?                                                                                              1 compile error
```

**Comment by wewman** [comment]
``error: syntax error, unexpected '?', expecting $end
.[] | .threads | .[] | if (.com + "\n" + .sub | test( $regrex;"i" )) then .no  else empty end?                                                                                              1 compile error
``

**Comment by 813gan** [comment]
try to remove '?' in line 
`jq --arg regrex "$regrex" '.[] | .threads | .[] | if (.com + "\n" + .sub | test( $regrex;"i" )) then .no  else empty end**?** ')`
Which jq version do You use? This code works on my machine.
My jq -v : jq-1.5

**Comment by wewman** [comment]
I have 1.4. I can install 1.5, but let me test if removing the '?' will work.

**Comment by wewman** [comment]
Yeah, I guess `test` is a 1.5 thing. It now says that `test` is not defined.

**Comment by 813gan** [comment]
Looks like we need to add dependency on >=jq-1.5 .

**Pull request merged**
